/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author proto
 */
public class JDlgRhgProdutos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgRhgProdutos.class.getName());

    /**
     * Creates new form JDlgRhgProdutos
     * @param parent
     * @param modal
     */
  public JDlgRhgProdutos(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();

    setLocationRelativeTo(null);

    setIconImage(new javax.swing.ImageIcon(
        getClass().getResource("/img/produto_1.png")
    ).getImage());

    desabilitarCampos();
    habilitarBotoesInicial();
}     
private void habilitarCampos() {
    txtNome.setEnabled(true);
    txtDescricao.setEnabled(true);
    cmbCategoria.setEnabled(true);
    txtMarca.setEnabled(true);
    txtCodigoBarras.setEnabled(true);
    txtPrecoCompra.setEnabled(true);
    txtPrecoVenda.setEnabled(true);
    txtQuantidade.setEnabled(true);
    txtEstoqueMinimo.setEnabled(true);
    txtUnidade.setEnabled(true);
    txtDataCadastro.setEnabled(true);
    cmbFornecedor.setEnabled(true);
    txtLocalizacao.setEnabled(true);
    chkAtivo.setEnabled(true);
}

private void desabilitarCampos() {
    txtIdProduto.setEnabled(false);
    txtNome.setEnabled(false);
    txtDescricao.setEnabled(false);
    cmbCategoria.setEnabled(false);
    txtMarca.setEnabled(false);
    txtCodigoBarras.setEnabled(false);
    txtPrecoCompra.setEnabled(false);
    txtPrecoVenda.setEnabled(false);
    txtQuantidade.setEnabled(false);
    txtEstoqueMinimo.setEnabled(false);
    txtUnidade.setEnabled(false);
    txtDataCadastro.setEnabled(false);
    cmbFornecedor.setEnabled(false);
    txtLocalizacao.setEnabled(false);
    chkAtivo.setEnabled(false);
}

private void limparCampos() {
    txtIdProduto.setText("");
    txtNome.setText("");
    txtDescricao.setText("");
    cmbCategoria.setSelectedIndex(0);
    txtMarca.setText("");
    txtCodigoBarras.setText("");
    txtPrecoCompra.setText("");
    txtPrecoVenda.setText("");
    txtQuantidade.setText("");
    txtEstoqueMinimo.setText("");
    txtUnidade.setText("");
    txtDataCadastro.setText("");
    cmbFornecedor.setSelectedIndex(0);
    txtLocalizacao.setText("");
    chkAtivo.setSelected(false);
}

private void habilitarBotoesInicial() {
    btnIncluir.setEnabled(true);
    btnPesquisar.setEnabled(true);

    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnConfirmar.setEnabled(false);
    btnCancelar.setEnabled(false);
}

private void habilitarBotoesEdicao() {
    btnIncluir.setEnabled(false);
    btnPesquisar.setEnabled(false);
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);

    btnConfirmar.setEnabled(true);
    btnCancelar.setEnabled(true);
}

private void habilitarBotoesPesquisa() {
    btnIncluir.setEnabled(true);
    btnPesquisar.setEnabled(true);
    btnAlterar.setEnabled(true);
    btnExcluir.setEnabled(true);
    btnConfirmar.setEnabled(false);
    btnCancelar.setEnabled(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosProdutos = new javax.swing.JPanel();
        lblIdProduto = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        lblPrecoVenda = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        txtPrecoCompra = new javax.swing.JTextField();
        lblPrecoCompra = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblEstoqueMinimo = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        lblUnidade = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtEstoqueMinimo = new javax.swing.JTextField();
        lblLocalizacao = new javax.swing.JLabel();
        lblAtivo = new javax.swing.JLabel();
        chkAtivo = new javax.swing.JCheckBox();
        lblDataCadastro = new javax.swing.JLabel();
        txtLocalizacao = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbFornecedor = new javax.swing.JComboBox<>();
        pnlBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        lblIdProduto.setText("ID:");

        txtIdProduto.addActionListener(this::txtIdProdutoActionPerformed);

        lblNome.setText("Nome:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        lblDescricao.setText("Descrição:");

        txtDescricao.addActionListener(this::txtDescricaoActionPerformed);

        txtPrecoVenda.addActionListener(this::txtPrecoVendaActionPerformed);

        lblCodigoBarras.setText("Código de Barras.:");

        lblCategoria.setText("Categoria:");

        lblMarca.setText("Marca:");

        txtDataCadastro.addActionListener(this::txtDataCadastroActionPerformed);

        lblPrecoVenda.setText("Preço de venda:");

        txtPrecoCompra.addActionListener(this::txtPrecoCompraActionPerformed);

        lblPrecoCompra.setText("Preço de compra:");

        txtMarca.addActionListener(this::txtMarcaActionPerformed);

        lblEstoqueMinimo.setText("Estoque mínimo:");

        txtUnidade.addActionListener(this::txtUnidadeActionPerformed);

        lblUnidade.setText("Unidade:");

        lblFornecedor.setText("Fornecedor:");

        txtQuantidade.addActionListener(this::txtQuantidadeActionPerformed);

        lblQuantidade.setText("Quantidade em estoque:");

        txtEstoqueMinimo.addActionListener(this::txtEstoqueMinimoActionPerformed);

        lblLocalizacao.setText("Localização:");

        lblAtivo.setText("Ativo:");

        chkAtivo.addActionListener(this::chkAtivoActionPerformed);

        lblDataCadastro.setText("Data de cadastro:");

        txtLocalizacao.addActionListener(this::txtLocalizacaoActionPerformed);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDadosProdutosLayout = new javax.swing.GroupLayout(pnlDadosProdutos);
        pnlDadosProdutos.setLayout(pnlDadosProdutosLayout);
        pnlDadosProdutosLayout.setHorizontalGroup(
            pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMarca)
                                    .addComponent(lblDataCadastro)
                                    .addComponent(lblLocalizacao)
                                    .addComponent(lblCategoria))
                                .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                    .addComponent(lblDescricao)
                                    .addGap(42, 42, 42)))
                            .addComponent(lblIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lblFornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276)
                                .addComponent(lblAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkAtivo)
                                .addGap(0, 108, Short.MAX_VALUE))
                            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosProdutosLayout.createSequentialGroup()
                                                .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCodigoBarras)
                                                    .addComponent(lblPrecoVenda)
                                                    .addComponent(lblEstoqueMinimo)
                                                    .addComponent(lblUnidade))
                                                .addGap(70, 70, 70)
                                                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtUnidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                                        .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblPrecoCompra)))
                                    .addComponent(txtLocalizacao))
                                .addContainerGap())))
                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantidade)
                        .addContainerGap())))
        );
        pnlDadosProdutosLayout.setVerticalGroup(
            pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecoCompra)
                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecoVenda))
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstoqueMinimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidade)))
                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDataCadastro))
                            .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosProdutosLayout.createSequentialGroup()
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocalizacao)
                            .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAtivo)
                            .addComponent(lblFornecedor)
                            .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(chkAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(this::btnIncluirActionPerformed);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDadosProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDadosProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdutoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoVendaActionPerformed

    private void txtDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCadastroActionPerformed

    private void txtPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCompraActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtEstoqueMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueMinimoActionPerformed

    private void chkAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAtivoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       javax.swing.JOptionPane.showMessageDialog(this, "Produto confirmado com sucesso!");
    limparCampos();
    desabilitarCampos();
    habilitarBotoesInicial();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        
    limparCampos();
    habilitarCampos();
    habilitarBotoesEdicao();
    txtNome.requestFocus();

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       habilitarCampos();
    habilitarBotoesEdicao();
    txtNome.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       limparCampos();
    desabilitarCampos();
    habilitarBotoesInicial();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       javax.swing.JOptionPane.showMessageDialog(this, "Exclusão ainda não implementada.");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
     
    txtIdProduto.setText("1");
    txtNome.setText("Arroz 5kg");
    txtDescricao.setText("Arroz branco tipo 1");
    cmbCategoria.setSelectedIndex(0);
    txtMarca.setText("indiozinho ");
    txtCodigoBarras.setText("67676767676767");
    txtPrecoCompra.setText("67.67");
    txtPrecoVenda.setText("67.67");
    txtQuantidade.setText("67");
    txtEstoqueMinimo.setText("67");
    txtUnidade.setText("UN");
    txtDataCadastro.setText("67/67/6767");
    cmbFornecedor.setSelectedIndex(0);
    txtLocalizacao.setText("Prateleira A67");
    chkAtivo.setSelected(true);

    desabilitarCampos();
    habilitarBotoesPesquisa();

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtLocalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDlgRhgProdutos dialog = new JDlgRhgProdutos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbFornecedor;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstoqueMinimo;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlDadosProdutos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtLocalizacao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables
}
