/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author proto
 */
public class JFrmRhgPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrmRhgPrincipal.class.getName());

    /**
     * Creates new form JFrmRhgPrincipal
     */
public JFrmRhgPrincipal() {
    initComponents();

    setLocationRelativeTo(null);
    setExtendedState(MAXIMIZED_BOTH);

 
    setIconImage(new javax.swing.ImageIcon(
        getClass().getResource("/img/loja_sapatos.png")
    ).getImage());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuMovimentos = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Sapatos - Gomes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        menuCadastros.setMnemonic('C');
        menuCadastros.setText("Cadastros");

        menuUsuarios.setMnemonic('U');
        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(this::menuUsuariosActionPerformed);
        menuCadastros.add(menuUsuarios);

        menuClientes.setMnemonic('L');
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(this::menuClientesActionPerformed);
        menuCadastros.add(menuClientes);

        menuFornecedores.setMnemonic('F');
        menuFornecedores.setText("Fornecedores");
        menuFornecedores.addActionListener(this::menuFornecedoresActionPerformed);
        menuCadastros.add(menuFornecedores);

        menuProdutos.setMnemonic('P');
        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(this::menuProdutosActionPerformed);
        menuCadastros.add(menuProdutos);

        menuCategorias.setMnemonic('G');
        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(this::menuCategoriasActionPerformed);
        menuCadastros.add(menuCategorias);

        jMenuBar1.add(menuCadastros);

        menuMovimentos.setMnemonic('M');
        menuMovimentos.setText("Movimentos");

        jMenuItem6.setMnemonic('V');
        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        menuMovimentos.add(jMenuItem6);

        jMenuItem7.setMnemonic('O');
        jMenuItem7.setText("Compras");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        menuMovimentos.add(jMenuItem7);

        jMenuBar1.add(menuMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
    
    JDlgRhgUsuarios tela = new JDlgRhgUsuarios(this, true);
    tela.setVisible(true);

    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

    javax.swing.JOptionPane.showMessageDialog(this, "Tela de vendas ainda não implementada.");

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedoresActionPerformed
  
    JDlgRhgFornecedores tela = new JDlgRhgFornecedores(this, true);
    tela.setVisible(true);

    }//GEN-LAST:event_menuFornecedoresActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed

    JDlgRhgClientes tela = new JDlgRhgClientes(this, true);
    tela.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
    javax.swing.JOptionPane.showMessageDialog(this, "Tela de compras ainda não implementada.");

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
      JDlgRhgProdutos tela = new JDlgRhgProdutos(this, true);
tela.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        JDlgRhgCategorias tela = new JDlgRhgCategorias(this, true);
tela.setVisible(true);
    }//GEN-LAST:event_menuCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new JFrmRhgPrincipal().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuFornecedores;
    private javax.swing.JMenu menuMovimentos;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
